# Generated by Django 3.2.8 on 2023-02-05 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_alter_user_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='电话号码'),
        ),
    ]
