# Generated by Django 3.2.8 on 2023-05-29 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('unpaid', '待支付'), ('unused', '待使用'), ('used', '已使用'), ('refund_pending', '待退款'), ('refunded', '已退款')], default='unpaid', max_length=20),
        ),
    ]
