# Generated by Django 3.2.8 on 2023-06-01 03:32

from django.db import migrations
import wangeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_travel_is_popular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='description',
            field=wangeditor.fields.WangRichTextField(),
        ),
    ]
