# Generated by Django 3.2.8 on 2023-02-02 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Museum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('website', models.URLField()),
                ('areaid', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': '博物馆',
                'db_table': 'museum',
            },
        ),
    ]
