# Generated by Django 3.2.8 on 2023-02-02 11:50

from django.db import migrations, models
import music_room.models


class Migration(migrations.Migration):

    dependencies = [
        ('music_room', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default=music_room.models.generate_code, max_length=8, unique=True),
        ),
    ]
