# Generated by Django 3.2.8 on 2023-11-28 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('body', models.TextField()),
                ('valid', models.BooleanField(default=True, verbose_name='page status')),
            ],
            options={
                'verbose_name': '页面详情',
                'db_table': 'page_detail',
            },
        ),
    ]
