# Generated by Django 3.2.8 on 2023-11-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_alter_page_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='type',
            field=models.CharField(choices=[('mdx', 'MDX'), ('html', 'Html')], default='mdx', max_length=10),
        ),
    ]
