# Generated by Django 3.2.8 on 2023-12-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_page_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='title',
            field=models.CharField(default='', max_length=255, verbose_name='page title'),
        ),
    ]
