# Generated by Django 3.2.8 on 2024-11-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_management', '0003_auto_20241122_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='gift_status',
            field=models.CharField(choices=[('N', 'Not a gift'), ('G', 'Is a gift')], default='N', max_length=1),
        ),
    ]
