# Generated by Django 3.2.8 on 2022-04-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='article title')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='article create_time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='article update_time')),
                ('body', models.TextField()),
                ('is_show', models.BooleanField(default=True, verbose_name='article show status')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='文章类别')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='类别创建时间')),
            ],
        ),
    ]
