# Generated by Django 3.2.8 on 2022-04-15 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '文章详情'},
        ),
        migrations.AlterModelTable(
            name='article',
            table='article_detail',
        ),
    ]
