# Generated by Django 3.2.8 on 2022-04-15 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20220415_1734'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecategory',
            options={'verbose_name': '文章分类'},
        ),
        migrations.AlterModelTable(
            name='articlecategory',
            table='article_category',
        ),
    ]
