# Generated by Django 3.2.8 on 2022-04-24 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0004_auto_20220415_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecategory',
            name='level',
            field=models.IntegerField(default=1, verbose_name='目录级别'),
        ),
        migrations.AlterField(
            model_name='article',
            name='auth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='article.articlecategory'),
        ),
    ]
