# Generated by Django 3.2.8 on 2022-04-24 12:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0005_auto_20220424_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecategory',
            name='parent_title',
            field=models.CharField(blank=True, max_length=100, verbose_name='父目录'),
        ),
        migrations.AddField(
            model_name='articlecategory',
            name='path',
            field=models.CharField(blank=True, max_length=512, verbose_name='分类路径'),
        ),
        migrations.AlterField(
            model_name='articlecategory',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='文章类别'),
        ),
        migrations.AlterUniqueTogether(
            name='article',
            unique_together={('auth', 'title')},
        ),
    ]
