# Generated by Django 3.2.8 on 2025-02-11 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20230211_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='栏目名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='栏目创建时间')),
            ],
            options={
                'verbose_name': '文章栏目',
                'db_table': 'article_category',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='articles', to='article.ArticleCategory'),
        ),
    ]
