# Generated by Django 3.2.8 on 2023-11-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_alter_article_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='type',
            field=models.CharField(choices=[('mdx', 'MDX'), ('html', 'Html')], default='mdx', max_length=10),
        ),
    ]
