# Generated by Django 3.2.8 on 2025-02-11 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_auto_20250211_1122'),
        ('article', '0009_article_type'),
    ]

    operations = [
    ]
