# Generated by Django 3.2.8 on 2023-04-19 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255)),
                ('question', models.TextField()),
                ('url', models.URLField(max_length=255)),
                ('answer', models.URLField(max_length=255)),
                ('tip', models.TextField()),
                ('userAnswer', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
