# Generated by Django 3.2.8 on 2023-04-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='options',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='tip',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='url',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
