# Generated by Django 3.2.8 on 2023-04-26 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_alter_question_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('scan', '浏览题'), ('single_choice', '单选题'), ('multi_choice', '多选题')], max_length=255),
        ),
    ]
