# Generated by Django 3.2.8 on 2023-05-26 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_auto_20230426_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('scan', '扫码题'), ('single_choice', '单选题'), ('multi_choice', '多选题')], max_length=255),
        ),
    ]
