# Generated by Django 3.2.8 on 2023-04-19 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaderboard',
            old_name='name',
            new_name='username',
        ),
    ]
