# Generated by Django 3.2.8 on 2022-04-10 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='img_url',
            field=models.ImageField(max_length=255, upload_to='', verbose_name='img url'),
        ),
    ]
