# Generated by Django 3.2.8 on 2022-04-10 12:01

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_banner_img_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='NarBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='nav title')),
                ('orders', models.IntegerField(default=1, verbose_name='nav order')),
                ('link_url', models.CharField(max_length=500, verbose_name='nav url')),
                ('is_show', models.BooleanField(default=True, verbose_name='nav show status')),
                ('position', models.IntegerField(choices=[(1, 'top nav'), (2, 'bottom nav')], verbose_name='nav position')),
                ('is_insite', models.BooleanField(default=True, verbose_name='是否为站内导航')),
            ],
            options={
                'verbose_name': '导航栏',
                'db_table': 'navbar',
            },
            bases=(home.models.BaseModel, models.Model),
        ),
        migrations.AlterField(
            model_name='banner',
            name='img_url',
            field=models.ImageField(max_length=255, upload_to='banner', verbose_name='img url'),
        ),
    ]
